name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run typecheck
        run: pnpm run tsc -- --noEmit

      - name: Run lint
        run: pnpm run lint
